from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from sandbox.sandbox import Sandbox


class StrictBaseModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class CheckResult(StrictBaseModel):
    success: bool
    score: float
    score_unit: str
    feedback: str | None
    feedback_image_paths: list[str] = Field(
        default_factory=list,
        description="Absolute paths to PNG files generated by the check. "
        "The harness embeds these as vision content in the next iteration's "
        "user message when the check has feedback=true.",
    )


class ConfigTask(StrictBaseModel):
    name: str = Field(description="Name of the experiment task")
    instructions: str = Field(description="Instructions to the llm")
    iterations: int = Field(
        description="Number of successive attempts to give the llm (each attempt lets it call tools and when it's done, the checks are run and the results passed to the next attempt)"
    )
    trials: int = Field(description="Repeat the experiment trials number of times")
    max_tool_calls: int = Field(
        description="Maximum number of tool calls for each attempt"
    )


class ConfigCheck(StrictBaseModel):
    name: str = Field(
        description="The python file in the checks folder implementing the check"
    )
    feedback: bool = Field(
        description="True if the check's feedback (text + graphs) should be passed to the agent. "
        "When False, only success is shown; score dicts from measurement checks are also suppressed."
    )
    description: str | None = Field(
        default=None,
        description="Human-readable explanation of what this check does, shown to the agent in the system prompt.",
    )
    params: dict[str, Any] = Field(
        default_factory=dict,
        description="YAML-fixed parameters merged into agent-supplied inputs before the check runs. "
        "These fields are excluded from the agent's union schema — the agent must not set them.",
    )
    depends_on: list[str] = Field(
        default_factory=list,
        description="Names of checks that must have passed (success=True) for this check to run. "
        "If any dependency failed, this check is skipped and recorded as skipped.",
    )


class ConfigPermissions(StrictBaseModel):
    read_files: bool = Field(
        description="Whether the LLM should be able to read files from the sandbox"
    )
    write_files: bool = Field(
        description="Whether the LLM should be able to write files to the sandbox"
    )
    code: bool = Field(
        description="Whether the LLM should be able to execute code in the sandbox (if enabled, read/write files don't really matter)"
    )
    network: bool = Field(
        description="Whether the LLM should be able to access the network from the sandbox"
    )


class ConfigFile(StrictBaseModel):
    dst: str = Field(description="The path within the sandbox to copy to")
    src: str = Field(description="The path to the file or directory to copy over")


class ConfigEnvironment(StrictBaseModel):
    permissions: ConfigPermissions
    tools: list[str] = Field(description="List of names of files in the tools folder")
    files: list[ConfigFile] = Field(
        description="List of file or directory assets to be copied over to the sandbox"
    )


class Config(StrictBaseModel):
    task: ConfigTask
    checks: list[ConfigCheck]
    environment: ConfigEnvironment


class RunState(StrictBaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid")

    config: Config
    sandbox: Sandbox
    trial_index: int = 0
    iteration_index: int = 0
    metadata: dict[str, Any] = Field(default_factory=dict)
    results_by_iteration: list[dict[str, CheckResult]] = Field(
        description="for each iteration, a map from check name to CheckResult"
    )
